language: node_js
node_js:
  - "10"
cache:
  directories:
    - node_modules

install:
  - npm install
  - npm run build

deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_ACCESS_TOKEN
  target-branch: gh-pages
  local-dir: dist
  fqdn: onibusufmg.com
  on:
    branch: master
